name: Build and deploy Spring Boot app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Move up one directory so Maven can find pom.xml
      - name: Move to correct folder
        run: cd ..

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 👇 Skip tests to avoid PostgreSQL connection timeout
      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      # ✅ NEW STEP — Azure Login (this is what was missing)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      # ✅ Deploy your JAR to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "taskmanager-api-backend"
          package: target/*.jar
